apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: jellycat-secret-store
spec:
  provider:
    # Example: HashiCorp Vault (KV v2). Install the Vault Helm chart and configure auth first.
    # Docs: https://external-secrets.io/latest/provider/hashicorp-vault/
    vault:
      server: "https://vault.yourdomain:8200"  # Vault address
      path: "kv"                                # Mount path of your KV engine
      version: "v2"                             # KV engine version
      auth:
        # Recommended: Kubernetes auth method in Vault (set role to your configured one)
        kubernetes:
          mountPath: "/v1/auth/kubernetes"     # Vault k8s auth mount path
          role: "externalsecrets"               # Vault role bound to service account
          serviceAccountRef:
            name: externalsecrets-sa
            namespace: jellycat
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: social-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: jellycat-secret-store
  target:
    name: social-secrets
  data:
    # For Vault KV v2, 'key' is '<mount>/data/<path>' when using API, but External Secrets
    # takes care of v2 data path; you supply the logical path under the mount.
    - secretKey: reddit_client_id
      remoteRef:
        key: jellycat/social
        property: REDDIT_CLIENT_ID
    - secretKey: reddit_client_secret
      remoteRef:
        key: jellycat/social
        property: REDDIT_CLIENT_SECRET
    - secretKey: reddit_user_agent
      remoteRef:
        key: jellycat/social
        property: REDDIT_USER_AGENT
    - secretKey: twitter_api_key
      remoteRef:
        key: jellycat/social
        property: TWITTER_API_KEY
    - secretKey: twitter_api_secret
      remoteRef:
        key: jellycat/social
        property: TWITTER_API_SECRET
    - secretKey: twitter_access_token
      remoteRef:
        key: jellycat/social
        property: TWITTER_ACCESS_TOKEN
    - secretKey: twitter_access_token_secret
      remoteRef:
        key: jellycat/social
        property: TWITTER_ACCESS_TOKEN_SECRET
    - secretKey: fb_access_token
      remoteRef:
        key: jellycat/social
        property: FB_ACCESS_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: jellycat-secret-store
  target:
    name: clickhouse-secrets
  data:
    - secretKey: password
      remoteRef:
  key: jellycat/clickhouse
  property: CLICKHOUSE_PASSWORD
